# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-01 21:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171129_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, validators=[profiles.models.AgeValidator]),
        ),
    ]
