# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.IntegerField(blank=True, choices=[(1, 'need'), (2, 'pantry'), (3, 'fridge'), (4, 'gone')], default=4)),
                ('new_status', models.IntegerField(choices=[(1, 'need'), (2, 'pantry'), (3, 'fridge'), (4, 'gone')], default=1)),
                ('latest_change', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='misc_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='change',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_changes', to='items.Item'),
        ),
        migrations.AddField(
            model_name='change',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
