# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='new_status',
            new_name='current_status',
        ),
        migrations.AlterField(
            model_name='change',
            name='old_status',
            field=models.IntegerField(blank=True, choices=[(1, 'need'), (2, 'pantry'), (3, 'fridge'), (4, 'gone')], default=None),
        ),
    ]
