# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-29 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20170523_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
