# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0002_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='item',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='misc_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='list',
            name='fridge_key',
            field=models.CharField(default='fridge-key', max_length=30),
        ),
        migrations.AddField(
            model_name='list',
            name='members',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'have'), (2, 'need'), (3, 'want'), (4, 'need_more'), (5, 'removed')], default=2),
        ),
        migrations.AddField(
            model_name='reminder',
            name='fridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge', to='list.List'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
