# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20170505_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='fridge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list.List'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='fridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='list.List'),
        ),
    ]
