# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20170505_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list.List'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'need'), (2, 'want'), (3, 'have'), (4, 'more'), (5, 'removed')], default=1),
        ),
    ]
