# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20170505_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fridge',
            new_name='kitchen',
        ),
        migrations.RemoveField(
            model_name='list',
            name='fridge_key',
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'need'), (2, 'pantry'), (3, 'fridge'), (4, 'gone')], default=1),
        ),
    ]
