# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20170511_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='item',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='fridge',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='from_user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
