# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20170511_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
