# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-13 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20170523_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
