# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_list_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
